pipeline {
    agent any
    
    environment {
        DOCKERHUB_CREDENTIALS = credentials('hub.docker.com') 
    }
    
    stages {
        stage("Git Checkout") {
            steps {
                git url: 'https://github.com/thecyberbaby/three-tier-app.git', branch: 'main'
                echo 'Git Checkout Completed'
                sh "lsb_release -a"
            }
        }
        
        stage('Build Docker Image') {
            steps {
                sh "docker build -t thecyberbaby/frontend:$BUILD_NUMBER ./application-code/frontend"
                echo 'Build Image Completed'
            }
        }
        
        // Uncomment the Trivy Scan stage when ready
        // stage('Trivy Scan') {
        //     steps {
        //         sh 'trivy image --no-progress --severity HIGH,CRITICAL thecyberbaby/frontend:$BUILD_NUMBER'
        //     }
        // }
        
        // Uncomment the Login to Docker Hub stage when ready
        // stage('Login to Docker Hub') {
        //     steps {
        //         withCredentials([usernamePassword(credentialsId: 'hub.docker.com', usernameVariable: 'DOCKERHUB_CREDENTIALS_USR', passwordVariable: 'DOCKERHUB_CREDENTIALS_PSW')]) {
        //             sh "echo $DOCKERHUB_CREDENTIALS_PSW | docker login -u $DOCKERHUB_CREDENTIALS_USR --password-stdin"
        //             echo 'Login Completed'
        //         }
        //     }
        // }
        
        stage('Push Image to Docker Hub') {
            steps {
                sh "docker push thecyberbaby/frontend:$BUILD_NUMBER"
                echo 'Push Image Completed'
            }
        }
    }
    
    post {
        always {
            sh 'docker logout'
        }
    }
}
