pipeline {
    agent any
    
    environment {
        DOCKERHUB_CREDENTIALS = credentials('hub.docker.com') 
    }
    
    stages {
        stage("Git Checkout") {
            steps {
                git url: 'https://github.com/thecyberbaby/three-tier-app.git', branch: 'main'
                echo 'Git Checkout Completed'
                sh "lsb_release -a"
            }
        }
        
        stage('Build Docker Image') {
            steps {
                sh "docker build -t thecyberbaby/frontend:$BUILD_NUMBER ./application-code/frontend"
                echo 'Build Image Completed'
            }
        }
        
        // stage('Trivy Scan') {
        //     steps {
        //         sh 'trivy image --no-progress --severity HIGH,CRITICAL thecyberbaby/frontend-dev:$BUILD_NUMBER'
        //     }
        // }
        
        stage('Push to Docker Hub') {
            steps {
                script {
                    // Using docker.withRegistry to handle authentication securely without exposing creds
                    docker.withRegistry('https://index.docker.io/v1/', 'hub.docker.com') {
                        sh "docker push thecyberbaby/frontend:$BUILD_NUMBER"
                    }
                }
                echo 'Push Image Completed'
            }
        }
    }
    
    post {
        always {
            sh 'docker logout || true'
        }
    }
}
