apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend-3-tier
  namespace: three-tier
  annotations:
    instrumentation.opentelemetry.io/inject-nodejs: "openobserve-collector/openobserve"
spec:
  replicas: 1
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 25%
  selector:
    matchLabels:
      app: frontend-3-tier
  template:
    metadata:
      labels:
        app: frontend-3-tier
    spec:
      containers:
        - name: frontend
          image: thecyberbaby/frontend:1.0
          ports:
            - containerPort: 3000
