apiVersion: v1
kind: Service
metadata:
  name: frontend-service
spec:
  selector:
    app: frontend-3-tier
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000
      nodePort: 30002
  type: NodePort  # Change to 'ClusterIP' if you don't need external access
  