apiVersion: v1
kind: Service
metadata:
  name: frontend-service
spec:
  selector:
    app: frontend-3-tier  # Ensure this matches the labels in your frontend pod
  ports:
    - name: http
      port: 3000
      targetPort: 3000
